import dayjs from 'dayjs/esm';
import customParseFormat from 'dayjs/esm/plugin/customParseFormat';
import duration from 'dayjs/esm/plugin/duration';
import relativeTime from 'dayjs/esm/plugin/relativeTime';

// jhipster-needle-i18n-language-dayjs-imports - JHipster will import languages from dayjs here
import 'dayjs/esm/locale/en';
import 'dayjs/esm/locale/sq';
import 'dayjs/esm/locale/ar-ly';
import 'dayjs/esm/locale/hy-am';
import 'dayjs/esm/locale/be';
import 'dayjs/esm/locale/bn';
import 'dayjs/esm/locale/bg';
import 'dayjs/esm/locale/ca';
import 'dayjs/esm/locale/zh-cn';
import 'dayjs/esm/locale/zh-tw';
import 'dayjs/esm/locale/hr';
import 'dayjs/esm/locale/cs';
import 'dayjs/esm/locale/da';
import 'dayjs/esm/locale/nl';
import 'dayjs/esm/locale/et';
import 'dayjs/esm/locale/fa';
import 'dayjs/esm/locale/fi';
import 'dayjs/esm/locale/fr';
import 'dayjs/esm/locale/gl';
import 'dayjs/esm/locale/de';
import 'dayjs/esm/locale/el';
import 'dayjs/esm/locale/hi';
import 'dayjs/esm/locale/hu';
import 'dayjs/esm/locale/id';
import 'dayjs/esm/locale/it';
import 'dayjs/esm/locale/ja';
import 'dayjs/esm/locale/ko';
import 'dayjs/esm/locale/mr';
import 'dayjs/esm/locale/my';
import 'dayjs/esm/locale/pl';
import 'dayjs/esm/locale/pt-br';
import 'dayjs/esm/locale/pt';
import 'dayjs/esm/locale/pa-in';
import 'dayjs/esm/locale/ro';
import 'dayjs/esm/locale/ru';
import 'dayjs/esm/locale/sk';
import 'dayjs/esm/locale/sr';
import 'dayjs/esm/locale/si';
import 'dayjs/esm/locale/es';
import 'dayjs/esm/locale/sv';
import 'dayjs/esm/locale/tr';
import 'dayjs/esm/locale/ta';
import 'dayjs/esm/locale/te';
import 'dayjs/esm/locale/th';
import 'dayjs/esm/locale/uk';
import 'dayjs/esm/locale/uz';
import 'dayjs/esm/locale/uz-latn';
import 'dayjs/esm/locale/vi';

// DAYJS CONFIGURATION
dayjs.extend(customParseFormat);
dayjs.extend(duration);
dayjs.extend(relativeTime);
